-- 教师（辅导员）数据插入脚本
-- 生成时间: 2026-04-01 19:57:21
-- 教师数量: 50

INSERT INTO yx_user (username, password, real_name, nick_name, user_type, dept_name, grade, status, is_deleted) VALUES
  ('cao_p_linchuang_21', 'caopeng', '曹鹏', '曹鹏', 'teacher', '临床与基础医学院（基础医学研究所）', '2021级', 1, FALSE),
  ('cheng_d_linchuang_22', 'chengdan', '程丹', '程丹', 'teacher', '临床与基础医学院（基础医学研究所）', '2022级', 1, FALSE),
  ('yu_j_linchuang_23', 'yujianhua', '于建华', '于建华', 'teacher', '临床与基础医学院（基础医学研究所）', '2023级', 1, FALSE),
  ('xu_z_gongwei_21', 'xuzhiqiang', '徐志强', '徐志强', 'teacher', '公共卫生与健康管理学院', '2021级', 1, FALSE),
  ('guo_j_gongwei_22', 'guojuan', '郭娟', '郭娟', 'teacher', '公共卫生与健康管理学院', '2022级', 1, FALSE),
  ('yang_g_gongwei_23', 'yangguiying', '杨桂英', '杨桂英', 'teacher', '公共卫生与健康管理学院', '2023级', 1, FALSE),
  ('yuan_j_huaxue_22', 'yuanjie', '袁洁', '袁洁', 'teacher', '化学与制药工程学院', '2022级', 1, FALSE),
  ('liang_s_huaxue_23', 'liangshufen', '梁淑芬', '梁淑芬', 'teacher', '化学与制药工程学院', '2023级', 1, FALSE),
  ('he_b_yixuexx_21', 'hebin', '何斌', '何斌', 'teacher', '医学信息与人工智能学院', '2021级', 1, FALSE),
  ('luo_y_yixuexx_22', 'luoyuzhen', '罗玉珍', '罗玉珍', 'teacher', '医学信息与人工智能学院', '2022级', 1, FALSE),
  ('chen_j_yixuexx_23', 'chenjing', '陈静', '陈静', 'teacher', '医学信息与人工智能学院', '2023级', 1, FALSE),
  ('song_z_yibao_22', 'songzhiqiang', '宋志强', '宋志强', 'teacher', '医疗保障学院（山东省医疗保障研究院）', '2022级', 1, FALSE),
  ('ma_s_yibao_23', 'mashulan', '马淑兰', '马淑兰', 'teacher', '医疗保障学院（山东省医疗保障研究院）', '2023级', 1, FALSE),
  ('tang_j_guanli_22', 'tangjing', '唐静', '唐静', 'teacher', '医药管理学院', '2022级', 1, FALSE),
  ('gao_z_guanli_23', 'gaozhihua', '高志华', '高志华', 'teacher', '医药管理学院', '2023级', 1, FALSE),
  ('zhou_j_kouqiang_21', 'zhoujianhua', '周建华', '周建华', 'teacher', '口腔医学院', '2021级', 1, FALSE),
  ('liang_g_kouqiang_22', 'lianggang', '梁刚', '梁刚', 'teacher', '口腔医学院', '2022级', 1, FALSE),
  ('yu_j_kouqiang_23', 'yujian', '于健', '于健', 'teacher', '口腔医学院', '2023级', 1, FALSE),
  ('ceng_j_waiyu_22', 'cengjian', '曾健', '曾健', 'teacher', '外国语学院', '2022级', 1, FALSE),
  ('fu_j_waiyu_23', 'fujing', '傅静', '傅静', 'teacher', '外国语学院', '2023级', 1, FALSE),
  ('xu_j_dongwu_23', 'xujun', '徐军', '徐军', 'teacher', '实验动物学院（省实验动物中心）', '2023级', 1, FALSE),
  ('lin_j_huli_21', 'linjianhua', '林建华', '林建华', 'teacher', '护理学院', '2021级', 1, FALSE),
  ('guo_s_huli_22', 'guoshuzhen', '郭淑珍', '郭淑珍', 'teacher', '护理学院', '2022级', 1, FALSE),
  ('he_y_huli_23', 'heyumei', '何玉梅', '何玉梅', 'teacher', '护理学院', '2023级', 1, FALSE),
  ('shen_c_huli_24', 'shenchao', '沈超', '沈超', 'teacher', '护理学院', '2024级', 1, FALSE),
  ('xiao_l_fangshe_21', 'xiaolong', '萧龙', '萧龙', 'teacher', '放射学院', '2021级', 1, FALSE),
  ('zheng_f_fangshe_22', 'zhengfang', '郑芳', '郑芳', 'teacher', '放射学院', '2022级', 1, FALSE),
  ('wu_s_fangshe_23', 'wushuzhen', '吴淑珍', '吴淑珍', 'teacher', '放射学院', '2023级', 1, FALSE),
  ('luo_x_fangshe_24', 'luoxia', '罗霞', '罗霞', 'teacher', '放射学院', '2024级', 1, FALSE),
  ('hu_z_shengke_22', 'huzhiqiang', '胡志强', '胡志强', 'teacher', '生命科学学院', '2022级', 1, FALSE),
  ('wu_l_shengke_23', 'wuli', '吴丽', '吴丽', 'teacher', '生命科学学院', '2023级', 1, FALSE),
  ('sun_g_shengwu_23', 'sunguizhi', '孙桂芝', '孙桂芝', 'teacher', '生物医学科学学院（省医药生物技术研究中心）', '2023级', 1, FALSE),
  ('xu_h_yanke_22', 'xuhui', '许辉', '许辉', 'teacher', '眼科学院', '2022级', 1, FALSE),
  ('wang_x_yanke_23', 'wangxiulan', '王秀兰', '王秀兰', 'teacher', '眼科学院', '2023级', 1, FALSE),
  ('sun_y_yanke_24', 'sunyang', '孙洋', '孙洋', 'teacher', '眼科学院', '2024级', 1, FALSE),
  ('han_h_fuyi_21', 'hanhui', '韩辉', '韩辉', 'teacher', '第一附属医院（第一临床学院）', '2021级', 1, FALSE),
  ('xie_s_fuyi_22', 'xieshuhua', '谢淑华', '谢淑华', 'teacher', '第一附属医院（第一临床学院）', '2022级', 1, FALSE),
  ('zhu_y_fuer_21', 'zhuyuhua', '朱玉华', '朱玉华', 'teacher', '第二附属医院（第二临床学院）', '2021级', 1, FALSE),
  ('huang_y_fuer_22', 'huangyumei', '黄玉梅', '黄玉梅', 'teacher', '第二附属医院（第二临床学院）', '2022级', 1, FALSE),
  ('huang_l_yaoxue_21', 'huanglei', '黄磊', '黄磊', 'teacher', '药学院（药物研究所）', '2021级', 1, FALSE),
  ('feng_s_yaoxue_22', 'fengshuzhen', '冯淑珍', '冯淑珍', 'teacher', '药学院（药物研究所）', '2022级', 1, FALSE),
  ('chen_x_yaoxue_23', 'chenxiuying', '陈秀英', '陈秀英', 'teacher', '药学院（药物研究所）', '2023级', 1, FALSE),
  ('zhu_y_yundong_22', 'zhuyan', '朱艳', '朱艳', 'teacher', '运动医学与康复学院', '2022级', 1, FALSE),
  ('zhang_j_yundong_23', 'zhangjianjun', '张建军', '张建军', 'teacher', '运动医学与康复学院', '2023级', 1, FALSE),
  ('peng_l_zhongxin_21', 'pengling', '彭玲', '彭玲', 'teacher', '附属中心医院（济南中心临床学院）', '2021级', 1, FALSE),
  ('liu_x_zhongxin_22', 'liuxiaoming', '刘晓明', '刘晓明', 'teacher', '附属中心医院（济南中心临床学院）', '2022级', 1, FALSE),
  ('yang_b_shengli_21', 'yangbo', '杨波', '杨波', 'teacher', '附属省立医院（省立临床学院）', '2021级', 1, FALSE),
  ('lv_l_shengli_22', 'lvlong', '吕龙', '吕龙', 'teacher', '附属省立医院（省立临床学院）', '2022级', 1, FALSE),
  ('han_y_zhongliu_22', 'hanyufen', '韩玉芬', '韩玉芬', 'teacher', '附属肿瘤医院（肿瘤临床学院）', '2022级', 1, FALSE),
  ('wang_j_fangsheyx_23', 'wangjianguo', '王建国', '王建国', 'teacher', '预防医学科学学院（放射医学研究所）', '2023级', 1, FALSE);

-- 关联教师角色 (假设教师角色ID为 3)
INSERT INTO yx_user_role (user_id, role_id) SELECT id, 3 FROM yx_user WHERE user_type = 'teacher';