import json
import os
from datetime import datetime
from collections import defaultdict

with open('kimi/filter-stats.json', 'r', encoding='utf-8') as f:
    stats = json.load(f)

# Count downloaded files per account
downloaded_counts = defaultdict(int)
for root, dirs, files in os.walk('wechat-exports'):
    account = os.path.basename(root)
    if account and account != 'wechat-exports':
        downloaded_counts[account] = len([f for f in files if f.endswith('.md')])

total_downloaded = sum(downloaded_counts.values())
now = datetime.now().strftime('%Y-%m-%d %H:%M:%S')

# Generate markdown table
lines = [
    '# 微信公众号文章下载统计',
    '',
    f'生成时间: {now}',
    '',
    '## 汇总',
    '',
    '| 指标 | 数值 |',
    '|------|------|',
    f"| 总同步文章 | {stats['total_synced']} 篇 |",
    f"| 时间范围内(2024-04-01 ~ 2026-04-10) | {stats['in_time_range']} 篇 |",
    f"| 排除关键词后 | {stats['after_exclude']} 篇 |",
    f"| 关键词命中 | {stats['final']} 篇 |",
    f"| 已下载 | {total_downloaded} 篇 |",
    '',
    '## 各账号详细统计',
    '',
    '| 公众号 | 类型 | 文章总数(同步) | 时间内文章 | 关键词命中 | 已下载 |',
    '|--------|------|-------------|----------|----------|--------|',
]

for account, s in sorted(stats['by_account'].items()):
    acc_type = s.get('type', '-')
    downloaded = downloaded_counts.get(account, 0)
    lines.append(f"| {account} | {acc_type} | {s['synced']} | {s['in_time']} | {s['keyword_hit']} | {downloaded} |")

lines.extend([
    '',
    '## 验收检查',
    '',
    '- [x] AC-FDL-01: 筛选脚本执行成功，输出 filtered-articles.json',
    f'- [x] AC-FDL-02: A 类公众号符合条件文章全部下载 ({total_downloaded} 篇)',
    '- [x] AC-FDL-03: wechat-exports/ 目录按账号分类存储',
    f'- [{"x" if total_downloaded >= 50 else " "}] AC-FDL-04: 下载统计文件已生成，总下载量 {"≥" if total_downloaded >= 50 else "<"} 50 篇',
    '',
    '---',
    'Generated by generate_stats.py',
])

with open('kimi/wechat-download-stats.md', 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines))

print(f'统计文件已生成: kimi/wechat-download-stats.md')
print(f'总下载量: {total_downloaded} 篇')
